SELECT TOP (1000) [Id]
      ,[Name]
      ,[HierarchicalParent]
      ,[HierarchicalLevel]
      ,[HierarchicalOrder]
      ,[__CreatedBy]
      ,[__CreatedOn]
      ,[поликлиника]
      ,[стационар]
      ,[универсальные]
  FROM [ASMMS].[dbo].[_Первичка_процессы]
  WHERE [Name] LIKE '%Оценка реабилитационного%'